package models

import (
	"time"
)

// Task represents the database schema and JSON structure
type Task struct {
	// ID is a string to match the UUID generated by the frontend
	ID          string    `gorm:"primaryKey" json:"id"`
	Title       string    `gorm:"not null" json:"title"`
	Description string    `json:"description"`
	Status      string    `gorm:"default:todo" json:"status"`   // todo, in_progress, done
	Priority    string    `gorm:"default:medium" json:"priority"` // low, medium, high
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}